const TECH_TERMS_TRANSLITERATION = {
  // --- Original Terms ---
  'ai': "ây-ai",
  'api': "ây-pi-ai",
  'llm': "el-el-em",
  'tts': "ti-ti-ét",
  'gpt': "gi-pi-ti",
  'whisper': "uít-xpơ",
  'remotion': 'ri-mô-sần',
  'video': 'vi-đê-ô',
  'marketing': 'mác-két-tinh',
  'dashboard': 'đát-bót',
  'animation': 'a-ni-mei-sơn',
  'avatar': 'a-va-ta',
  'website': 'oét-sai',
  'logo': 'lô-gô',
  'component': 'com-po-nơnt',
  'framework': 'fờ-rem-uốc',
  'timeline': 'tai-lai',
  'audio': 'au-đi-ô',
  'mp4': 'em-pi-bốn',
  'mp3': 'em-pi-ba',
  'premiere': 'pờ-re-mi-e',
  'capcut': 'cáp-cắt',
  'photoshop': 'phô-tô-thóp',
  'illustrator': 'in-lút-trây-tơ',
  'canva': 'can-va',
  'figma': 'phích-ma',
  'front-end': 'phờ-rơn-en',
  'back-end': 'bách-en',
  'native': 'nây-típ',
  'gateway': 'gết-uê',
  'service': 'sơ-vít',
  'cloud': 'clao',
  'serverless': 'sơ-vơ-lét',
  'verceljs': 'vơ-xen-chây-ét',
  'supabase': 'xu-pa-bây',
  'tailwind': 'teo-uin',
  'rag': 'rác',
  'hust': "hớt",
  'seee': "se",
  'rikkei': "rì-kây",
  'academy': "a-ka-đê-mi",
  'mcp': "em-ci-pi",
  'usb-c': "ui-ét-bi-ci",
  'drive': "đì-vai",
  'google': "gu-gồ",
  'model': "mo-đồ",
  'context': "con-tếch",
  'protocol': "pô-tô-cô",
  'paper': "pây-pơ",
  'abstract': "áp-trách",
  'iot': "ai-ô-ti",
  'internet': "in-tơ-nét",
  'zoom': "rum",
  'wi-fi': "uai-fai",
  'arm': "a-r-m",
  'of': "ợp",
  'thinks': 'thinh',
  'memory': "mem-mo-ri",
  'hub': "hắp",
  'follow': "fo-lâu",
  'course': "cót",
  'trend': "chen",
  'open': 'âu-pơn',
  'openai': 'âu-pơn-ây-ai',
  'reinforcement': "ri-in-pho-mừn",
  'learning': "lơn-ing",
  'meta': "mê-ta",
  'backend': "bách-en",
  'software': "sóp-woe",
  'engineer': "en-rin-nia",
  'programmer': "pro-gram-mơ",
  'developer': "đi-vơ-lốp-bơ",
  'cursor': "cơ-sờ",
  'c': 'xi',
  'c++': 'xi cộng cộng',
  'cplusplus': 'xi cộng cộng',
  'c#': 'xi sáp',
  'csharp': 'xi sáp',
  'real-time': "riu-tham",
  'spacex': "sờ-pây-ích",
  'realtime': 'riu-tham',
  'selfie': "seo-phi",
  'photo': "phô-tô",
  'ai-native': "ây-ai-lây-típ",
  '3d': 'ba đê',
  '2d': 'hai đê',
  '4d': 'bốn đê',
  '5g': 'năm gờ',
  '4g': 'bốn gờ',
  'ar': 'ây-a',
  'vr': 'vi-a',
  'mr': 'em-a',
  'xr': 'ích-a',
  'gpu': 'gờ-pi-diu',
  'cpu': 'xê-pi-diu',
  'ram': 'ram',
  'ssd': 'ét-ét-đi',
  'hdd': 'hát-đi-đi',
  'usb': 'diu-ét-bi',
  'hdmi': 'hát-đi-em-ai',
  '4k': 'bốn cây',
  '8k': 'tám cây',
  '1080p': 'một không tám không pi',
  '720p': 'bảy hai không pi',
  'fps': 'phờ-pi-ét',
  'sdk': 'ét-đi-cây',
  'ide': 'ai-đi-i',
  'saas': 'xát',
  'paas': 'pát',
  'iaas': 'ai-at',
  'b2b': 'bi tu bi',
  'b2c': 'bi tu xi',
  'roi': 'a-roi',
  'kpi': 'cây-pi-ai',
  'okr': 'âu-cây-a',
  'cto': 'xê-ti-âu',
  'ceo': 'xê-i-âu',
  'coo': 'xê-âu-âu',
  'llama': 'la-ma',
  'deepseek': 'đíp-sích',
  'claude': 'cờ-lau',
  'gemini': 'ge-mi-ni',
  'mistral': 'mít-trồ',
  'pytorch': 'pai-tót',
  'tensorflow': 'ten-sờ-phlâu',
  'huggingface': 'hắc-kinh-pheit',
  'langchain': 'lang-chên',
  'llamaindex': 'la-ma-in-đéch',
  'backpropagation': 'bắc-bờ-rô-ba-gây-sần',
  'gradient': 'gờ-rây-đi-ơnt',
  'transformer': 'trăn-pho-mơ',
  'attention': 'a-ten-sần',
  'bernhard': "bơn-hát",
  'kerbl': "cơ-bồ",

  // --- Newly Added Terms ---
  'sdlc': "es-đi-el-si",
  'ai-driven sdlc': "ây-ai đờ-roai-vừn es-đi-el-si",
  'js': "chây-es",
  'pr': "pi-ar",
  'prd': "pi-ar-đi",
  'ci/cd': "si-ai si-đi",
  'ga4': "gi-ây phô",
  'aeo': "ây-i-ô",
  'geo': "gi-i-ô",
  'it': "ai-ti",
  'qa': "kiu-ây",
  'ba': "bi-ây",
  'pm': "pi-em",
  'jd': "giê-đi",
  'adr': "ây-đi-ar",
  'dod': "đê-ô-đê",
  'ac': "ây-si",
  'icp': "ai-si-pi",
  'url': "u-ar-el",
  'https': "hát-tê-tê-pi-es",
  'pdf': "pi-đi-ef",
  'ui/ux': "u-ai yu-ec",
  'sql': "sơ-quần",
  'v8 engine': "vi-tám en-jin",
  'github': "gít-hắp",
  'claude code': "cờ-lót cốt",
  'claude code cli': "cờ-lót cốt si-el-ai",
  'claude 3.5 sonnet': "cờ-lót ba chấm năm son-nét",
  'sonnet 5': "son-nét năm",
  'opus 5': "ô-pớt năm",
  'cursor tab': "cơ-sơ táp",
  'deepseek r1': "đíp-xích ar-một",
  'deepseek v3': "đíp-xích vi-ba",
  'gemini 2.0 flash': "gie-mi-nai hai chấm không phờ-lát",
  'kimi 1.5': "ki-mi một chấm năm",
  'kimi k3': "ki-mi ca-ba",
  'chatgpt': "chét-gi-pi-ti",
  'anthropic': "ân-thờ-rô-pic",
  'google deepmind': "gút-gồ đíp-mai",
  'microsoft': "mai-crô-sóp",
  'uber': "u-bơ",
  'docker': "đốc-kơ",
  'devcontainer': "đev-côn-tai-nơ",
  'obsidian': "ọp-si-đi-ân",
  'husky': "hớt-sci",
  'newman cli': "niu-mần si-el-ai",
  'swagger': "sờ-wag-gơ",
  'duolingo': "đu-ô-ling-gô",
  'itviec': "ai-ti việc",
  'ieee spectrum': "ai-tháp-pồ-i sờ-pếch-trầm",
  'mit technology review': "em-ai-ti tếch-nô-lô-gi ri-viu",
  'rikkei academy': "rích-kei a-ca-đê-mi",
  'rikkeisoft': "rích-kei-sóp",
  'javascript': "gia-va-sờ-cơ-ríp",
  'generative coding': "gie-nơ-ra-típ cốt-đinh",
  'vibe coding': "vai-bơ cốt-đinh",
  'quiet failure': "quai-ợt phe-li-ơ",
  'spec-first': "sờ-pếch phớt",
  'task contract': "tát-xơ con-trắc",
  'review gate': "ri-viu gết",
  'context engineering': "côn-tếch en-gi-ni-ơ-ring",
  'guardrails': "gát-rai",
  'rollback': "rôn-bắc",
  'hallucination': "ha-lu-si-nei-shần",
  'reward hacking': "ri-wọt hắc-king",
  'memory leak': "me-mo-ri lích",
  'unit test': "yu-nít tết",
  'async/await': "ơ-xinh ơ-wết",
  'promise.all': "pờ-ro-mis chấm ô-l",
  'clean architecture': "cờ-lin a-ki-tếch-chơ",
  'git diff': "gít đíp",
  'git commit': "gít cóm-mít",
  'pull request': "pul ri-quết",
  'evidence log': "e-vi-đần-xơ lốc",
  'agent-readable': "ei-giần ri-đơ-bồ",
  'openapi spec': "ô-pân-ây-pi-ai sờ-pếch",
  'terminal': "tơ-mi-nần",
  'cli': "si-el-ai",
  'multi-agent': "măn-ti ei-giần",
  'secret': "si-crết",
  'token': "tô-cần",
  'license': "lai-xần",
  'codebase': "cốt-bây",
  'repo': "re-pô",
  'tech lead': "tếch lít",
  'fresher': "phờ-réch-shơ",
  'junior': "giu-ni-ơ",
  'senior': "si-ni-ơ",
  'microservice': "mai-crô-sơ-vít",
  'refactor': "ri-phắc-tơ",
  '.js': "chấm chây-es",
  'main.js': "mein chấm chây-es",
  '.env.example': "chấm i-vi-en chấm íc-xem-pồ",
  '.env': "chấm i-vi-en",
  'package.json': "pắc-ki-ch chấm giê-sơn",
  'dockerfile': "đốc-kơ phai",
  '.agents/product-marketing.md': "chấm ei-giần chấm pờ-rô-đắc mác-kê-ting chấm em-đi"
};

const TECH_TERMS_WHITELIST = new Set([
  'prompt', 'react', 'api', 'vite', 'nextjs', 'next.js', 'nodejs', 'node.js', 'javascript', 'typescript',
  'css', 'html', 'npm', 'json', 'sql', 'cli', 'git', 'github', 'docker', 'aws', 'vercel',
  'remotion', 'video', 'marketing', 'dashboard', 'animation', 'avatar', 'website', 'logo',
  'brand', 'component', 'framework', 'timeline', 'audio', 'mp4', 'mp3', 'client', 'server',
  'app', 'dev', 'build', 'deploy', 'code', 'database', 'ai', 'gpt', 'llm', 'agent', 'premiere',
  'capcut', 'photoshop', 'illustrator', 'canva', 'figma', 'ui', 'ux', 'front-end', 'back-end',
  'gpt-4', 'gpt-3', 'gpt4', 'gpt3',
  // Dynamic whitelist from new keys
  ...Object.keys(TECH_TERMS_TRANSLITERATION)
]);

module.exports = {
  TECH_TERMS_TRANSLITERATION,
  TECH_TERMS_WHITELIST
};
