const TECH_TERMS_TRANSLITERATION = {
  '.agents/product-marketing.md': 'chấm ei-giần chấm pờ-rô-đắc mác-kê-ting chấm em-đi',
  '.env': 'chấm i-vi-en',
  '.env.example': 'chấm i-vi-en chấm íc-xem-pồ',
  '.js': 'chấm chây-es',
  '1080p': 'một không tám không pi',
  '2d': 'hai đê',
  '3d': 'ba đê',
  '4d': 'bốn đê',
  '4g': 'bốn gờ',
  '4k': 'bốn cây',
  '5 whys': 'năm oai',
  '5g': 'năm gờ',
  '720p': 'bảy hai không pi',
  '8k': 'tám cây',
  'abstract': 'áp-trách',
  'ac': 'ê-si',
  'academy': 'a-ka-đê-mi',
  'acceptance criteria': 'ạc-sép-tần cờ-rai-ti-ri-a',
  'adr': 'ây-đi-ar',
  'aeo': 'ây-i-ô',
  'agent': 'ê-dần',
  'agent-readable': 'ei-giần ri-đơ-bồ',
  'agentic ai': 'ê-giần-tích ai',
  'agile': 'a-gai',
  'ai': 'ây-ai',
  'ai agent': 'ai ê-dần',
  'ai-augmented ba': 'ai oóc-men-tịt bi-ây',
  'ai-driven sdlc': 'ây-ai đờ-roai-vừn es-đi-el-si',
  'ai-native': 'ây-ai-lây-típ',
  'animation': 'a-ni-mei-sơn',
  'anthropic': 'ân-thờ-rô-pic',
  'antigravity ide': 'an-ti-gra-vi-ti ai-đi-i',
  'api': 'a-pi-ai',
  'app': 'áp',
  'app store': 'áp sờ-to',
  'ar': 'ây-a',
  'arm': 'a-r-m',
  'as-is': 'ét-i',
  'async/await': 'ơ-xinh ơ-wết',
  'attention': 'a-ten-sần',
  'audio': 'au-đi-ô',
  'audit log': 'o-đít lốc',
  'auto-reversal': 'rì-vơ-sồ tự động',
  'avatar': 'a-va-ta',
  'aws': 'ây-đờ-bờ-lu-ét',
  'b2b': 'bi tu bi',
  'b2b2c': 'bi tu bi tu xi',
  'b2c': 'bi tu xi',
  'ba': 'bi-ây',
  'back-end': 'bách-en',
  'backend': 'bách-en',
  'backlog': 'bách-lốc',
  'backpropagation': 'bắc-bờ-rô-ba-gây-sần',
  'bernhard': 'bơn-hát',
  'bpmn': 'b-p-m-n',
  'bpmn 2.0': 'bê-pê-em-en hai chấm không',
  'brainstorming': 'bờ-rên-stơ-ming',
  'brand': 'bờ-ren',
  'brd': 'bê-rờ-đê',
  'bridge se': 'bờ-rờ-ét-e',
  'brse': 'bờ-rít-gơ ét-i',
  'bug': 'bấc',
  'build': 'biu',
  'burndown chart': 'bơn-đao chạt',
  'business analyst': 'bi-di-nít a-na-lít',
  'c': 'xi',
  'c-level': 'xi lê-vồ',
  'c#': 'xi sáp',
  'c++': 'xi cộng cộng',
  'canva': 'can-va',
  'capcut': 'cáp-cắt',
  'cbap': 'c-b-a-p',
  'ccba': 'c-c-b-a',
  'cccd': 'căn cước công dân',
  'cd': 'si-ai si-đi',
  'ceo': 'xê-i-âu',
  'change request': 'chên rì-quét',
  'chatgpt': 'chát g-p-t',
  'ci': 'si-ai si-đi',
  'ci/cd': 'si-ai si-đi',
  'claude': 'cờ-lốt',
  'claude 3.5 sonnet': 'cờ-lót ba chấm năm son-nét',
  'claude ai': 'cờ-lốt ai',
  'claude code': 'cờ-lót cốt',
  'claude code cli': 'cờ-lót cốt si-el-ai',
  'clean architecture': 'cờ-lin a-ki-tếch-chơ',
  'cli': 'si-el-ai',
  'client': 'clai-ơn',
  'cloud': 'cờ-lao',
  'code': 'cốt',
  'codebase': 'cốt-bây',
  'codex': 'cô-đếch',
  'component': 'com-po-nơnt',
  'confluence': 'con-phơ-lu-ơn',
  'consent': 'cơn-xen',
  'context': 'con-tếch',
  'context engineering': 'côn-tếch en-gi-ni-ơ-ring',
  'coo': 'xê-âu-âu',
  'copilot': 'cô-pai-lợt',
  'core banking': 'co-banh-king',
  'coupon': 'cu-pon',
  'course': 'cót',
  'cpar': 'si-pi-ei-a',
  'cplusplus': 'xi cộng cộng',
  'cpu': 'xê-pi-diu',
  'cr': 'c-rờ',
  'credit': 'cờ-ré-đít',
  'csharp': 'xi sáp',
  'cskh': 'chăm sóc khách hàng',
  'css': 'c-s-s',
  'cto': 'xê-ti-âu',
  'cursor': 'cơ-sờ',
  'cursor tab': 'cơ-sơ táp',
  'daily scrum': 'đây-li sờ-cờ-răm',
  'dashboard': 'đát-bo',
  'data anonymization': 'đa-ta ơ-non-ni-mai-zây-sần',
  'data reconciliation': 'đa-ta rê-cơn-xi-li-ây-sần',
  'database': 'đa-ta-bây-xơ',
  'database index': 'đây-ta-bây in-đếch',
  'date range': 'đết rên',
  'db': 'đi-bi',
  'debit': 'đê-bít',
  'deep work': 'đíp uốc',
  'deepseek': 'đíp-sích',
  'deepseek r1': 'đíp-xích ar-một',
  'deepseek v3': 'đíp-xích vi-ba',
  'definition of done': 'đê-ô-đê',
  'definition of ready': 'đê-ô-ar',
  'deploy': 'đi-ploi',
  'dev': 'đép',
  'devcontainer': 'đev-côn-tai-nơ',
  'developer': 'đê-vê-lốp-pơ',
  'dfd': 'đi-ép-đi',
  'docker': 'đốc-kơ',
  'dockerfile': 'đốc-kơ phai',
  'documenter & supporter': 'đô-kiu-men-tơ & sắp-po-tơ',
  'dod': 'đê-ô-đê',
  'dor': 'đê-ô-ar',
  'downtime': 'đao-tai',
  'draw.io': 'đờ-rô-ai-ô',
  'drive': 'đì-vai',
  'dropdown': 'đờ-róp-đao',
  'duolingo': 'đu-ô-ling-gô',
  'dynamic qr': 'quy-rờ động',
  'e-commerce': 'í-com-mợt',
  'ecba': 'e-c-b-a',
  'edge cases': 'éc kê-sịt',
  'ehr': 'e-h-r',
  'ekyc': 'e-k-y-c',
  'elicitation': 'ê-li-si-tây-sần',
  'emr': 'e-m-r',
  'emvco': 'e-m-v-co',
  'engineer': 'en-rin-nia',
  'erd': 'e-rờ-đê',
  'eu': 'ê u',
  'evidence log': 'e-vi-đần-xơ lốc',
  'excel': 'éc-xen',
  'faceid': 'fe-ai-đi',
  'fallback': 'pho-bách',
  'figma': 'pích-ma',
  'fintech': 'fin-tếch',
  'fix bug': 'phích bấc',
  'flash sale': 'pờ-lát siu',
  'flowchart': 'pờ-lâu-chạt',
  'follow': 'fo-lâu',
  'fps': 'phờ-pi-ét',
  'framework': 'fờ-rem-uốc',
  'fresher': 'phờ-réch-shơ',
  'fresher ba': 'phơ-rét-shơ bi-ây',
  'front-end': 'phờ-rơn-en',
  'frontend': 'phờ-rơn-en',
  'fullstack': 'phun-xtắc',
  'ga4': 'gi-ây phô',
  'gap analysis': 'gáp a-na-ly-sít',
  'gateway': 'gết-uê',
  'gemini': 'ge-mi-ni',
  'gemini 2.0 flash': 'gie-mi-nai hai chấm không phờ-lát',
  'generative coding': 'gie-nơ-ra-típ cốt-đinh',
  'geo': 'gi-i-ô',
  'git': 'gít',
  'git commit': 'gít cóm-mít',
  'git diff': 'gít đíp',
  'github': 'gít-hắp',
  'given - when - then': 'ghi-vần - oen - đen',
  'google': 'gu-gồ',
  'google deepmind': 'gút-gồ đíp-mai',
  'google play': 'gút-gồ pờ-lay',
  'gpt': 'gi-pi-ti',
  'gpu': 'gờ-pi-diu',
  'gradient': 'gờ-rây-đi-ơnt',
  'guardrails': 'gát-rai',
  'hallucination': 'ha-lu-si-nei-shần',
  'hdd': 'hát-đi-đi',
  'hdmi': 'hát-đi-em-ai',
  'headhunter': 'hét-hăn-tơ',
  'healthtech': 'heo-tếch',
  'hipaa': 'híp-pa',
  'hl7 fhir': 'h-l-7 phơ',
  'hold balance': 'hâu ba-lần',
  'hotfix': 'hót-phích',
  'html': 'hát-tê-mờ-lờ',
  'https': 'hát-tê-tê-pi-es',
  'hub': 'hắp',
  'huggingface': 'hắc-kinh-pheit',
  'husky': 'hớt-sci',
  'hust': 'hớt',
  'iaas': 'ai-at',
  'icd-10': 'i-c-d-10',
  'icp': 'ai-si-pi',
  'ide': 'ai-đi-i',
  'ieee spectrum': 'ai-tháp-pồ-i sờ-pếch-trầm',
  'iiba': 'i-i-b-a',
  'illustrator': 'in-lút-trây-tơ',
  'impact assessment': 'im-pắc ơ-sét-mơn',
  'in-scope': 'in-sờ-cốp',
  'internet': 'in-tơ-nét',
  'iot': 'ai-ô-ti',
  'it': 'ai-ti',
  'itviec': 'ai-ti việc',
  'javascript': 'gia-va-sờ-cơ-ríp',
  'jd': 'giê-đi',
  'jira': 'ji-ra',
  'js': 'chây-es',
  'json': 'giê-sơn',
  'junior': 'giu-ni-ơ',
  'junior ba': 'giu-ni-ơ bi-ây',
  'kerbl': 'cơ-bồ',
  'kimi 1.5': 'ki-mi một chấm năm',
  'kimi k3': 'ki-mi ca-ba',
  'kpi': 'kê-pi-ai',
  'langchain': 'lang-chên',
  'lead ba': 'lít bi-ây',
  'learning': 'lơn-ing',
  'license': 'lai-xần',
  'llama': 'la-ma',
  'llamaindex': 'la-ma-in-đéch',
  'llm': 'el-el-em',
  'log': 'lốc',
  'logo': 'lô-gô',
  'low-code': 'lâu-cốt',
  'main.js': 'mein chấm chây-es',
  'marketing': 'mác-két-tinh',
  'mcp': 'em-ci-pi',
  'meeting minutes': 'mít-tinh mi-nút',
  'memory': 'mem-mo-ri',
  'memory leak': 'me-mo-ri lích',
  'mentor': 'men-tơ',
  'mermaid': 'mơ-mết',
  'meta': 'mê-ta',
  'microservice': 'mai-crô-sơ-vít',
  'microservices': 'mai-crô-xơ-vít',
  'microsoft': 'mai-crô-sóp',
  'miro': 'mi-rô',
  'mistral': 'mít-trồ',
  'mit technology review': 'em-ai-ti tếch-nô-lô-gi ri-viu',
  'mockup': 'móc-ắp',
  'model': 'mo-đồ',
  'moscow': 'mót-câu',
  'mp3': 'em-pi-ba',
  'mp4': 'em-pi-bốn',
  'mr': 'em-a',
  'multi-agent': 'măn-ti ei-giần',
  'mvp': 'em-vi-pi',
  'napas': 'na-pát',
  'native': 'nây-típ',
  'nda': 'n-d-a',
  'newman cli': 'niu-mần si-el-ai',
  'next.js': 'néch-chây-ét',
  'nextjs': 'néch-chây-ét',
  'no-code': 'nô-cốt',
  'node.js': 'nốt-chây-ét',
  'nodejs': 'nốt-chây-ét',
  'non-it': 'non ai-ti',
  'notion': 'nô-sần',
  'npm': 'en-pi-em',
  'obsidian': 'ốp-si-đi-ần',
  'of': 'ợp',
  'okr': 'âu-cây-a',
  'open': 'âu-pơn',
  'openai': 'âu-pơn-ây-ai',
  'openapi spec': 'ô-pân-ây-pi-ai sờ-pếch',
  'opus 5': 'ô-pớt năm',
  'order-taker': 'o-đơ tây-kơ',
  'otp': 'ô-tê-pê',
  'out-of-scope': 'ao-ốp-sờ-cốp',
  'paas': 'pát',
  'package.json': 'pắc-ki-ch chấm giê-sơn',
  'paper': 'pây-pơ',
  'parsing': 'pạt-xinh',
  'payload': 'pây-lốt',
  'payment gateway': 'pây-mơn gết-uê',
  'pci dss': 'pi-xi-ai đi-es-es',
  'pdf': 'pi-đi-ef',
  'persona': 'pơ-xô-na',
  'pet project': 'pét pờ-rô-giếch',
  'photo': 'phô-tô',
  'photoshop': 'phô-tô-thóp',
  'pm': 'pi-em',
  'pmi-pba': 'p-m-i p-b-a',
  'po': 'pi-ô',
  'poc': 'pi-ô-si',
  'popup': 'póp-ắp',
  'pos': 'p-o-s',
  'post-mortem meeting': 'pốt mo-tơm mít-tinh',
  'postman': 'pốt-mên',
  'powerpoint': 'pao-ơ-poi',
  'pr': 'pi-ar',
  'prd': 'pi-rờ-đê',
  'premiere': 'pờ-re-mi-e',
  'principal ba': 'pờ-rin-xi-pồ bi-ây',
  'problem-solver': 'pờ-rốp-lem xon-vơ',
  'product ba': 'pờ-rô-đắc bi-ây',
  'product backlog': 'pờ-rô-đắc bách-lốc',
  'product grooming': 'pờ-rô-đắc gờ-ru-ming',
  'product owner': 'pờ-rô-đắc ô-nơ',
  'programmer': 'pro-gram-mơ',
  'project': 'pờ-rô-giếch',
  'project manager': 'pờ-rô-giếch mê-ni-giơ',
  'promise.all': 'pờ-ro-mis chấm ô-l',
  'prompt': 'pờ-rôm',
  'prompting': 'pờ-rôm-tinh',
  'protocol': 'pô-tô-cô',
  'prototype': 'pờ-rô-tô-típ',
  'psm': 'p-s-m',
  'pspo': 'p-s-p-o',
  'pull request': 'pul ri-quết',
  'pytorch': 'pai-tót',
  'qa': 'ki-u-ê',
  'qc': 'ki-u-si',
  'qr': 'quy-rờ',
  'qr code': 'quy-rờ cốt',
  'quiet failure': 'quai-ợt phe-li-ơ',
  'rag': 'rác',
  'ram': 'ram',
  'rbac': 'r-b-a-c',
  'react': 'ri-ác',
  'read replica': 'rít rép-li-ca',
  'real-time': 'riu-tham',
  'realtime': 'ri-ơ-tai',
  'refactor': 'ri-phắc-tơ',
  'refactoring': 'ri-phắc-tơ-ring',
  'reinforcement': 'ri-in-pho-mừn',
  'release': 'rì-lít',
  'remotion': 'ri-mô-sần',
  'repo': 're-pô',
  'requirement': 'rì-quai-mơn',
  'retrospective': 'rê-tờ-rô-sờ-péc-típ',
  'review gate': 'ri-viu gết',
  'reward hacking': 'ri-wọt hắc-king',
  'rfp': 'ar-ép-pi',
  'rice scoring': 'rai-xơ sờ-co-ring',
  'rikkei': 'rì-kây',
  'rikkei academy': 'rích-kei a-ca-đê-mi',
  'rikkei education': 'rík-kei e-du-cay-sần',
  'rikkeisoft': 'rík-kei-xốp',
  'roadmap': 'rốt-mép',
  'roi': 'rờ-o-ai',
  'rollback': 'rôn-bắc',
  'root cause': 'rút cooc-zơ',
  'saas': 'xát',
  'scope': 'sờ-cốp',
  'scrum': 'sờ-cờ-răm',
  'scrum master': 'sờ-cờ-răm mát-xtơ',
  'sdk': 'ét-đi-cây',
  'sdlc': 'es-đi-el-si',
  'secret': 'si-crết',
  'seee': 'se',
  'selfie': 'seo-phi',
  'senior': 'si-ni-ơ',
  'senior ba': 'se-ni-ơ bi-ây',
  'server': 'sơ-vơ',
  'serverless': 'sơ-vơ-lét',
  'service': 'sơ-vít',
  'sms': 'ét-em-ét',
  'sms gateway': 'ét-em-ét ghết-oây',
  'software': 'sóp-woe',
  'solution analyst': 'sô-lu-sần a-na-lít',
  'solution architect': 'sô-lu-sần a-ki-tếch',
  'sonnet 5': 'son-nét năm',
  'sow': 'es-o-đắp-liêu',
  'spacex': 'sờ-pây-ích',
  'spec-first': 'sờ-pếch phớt',
  'spillover': 'sờ-pin-âu-vơ',
  'sprint': 'sờ-prin',
  'sprint backlog': 'sờ-prin bách-lốc',
  'sprint planning': 'sờ-prin pờ-lan-ning',
  'sql': 'ét-quy-en',
  'srs': 'ét-rờ-ét',
  'ssd': 'ét-ét-đi',
  'stakeholder': 'xờ-tếch-hâu-đơ',
  'star': 'sờ-ta',
  'static qr': 'quy-rờ tĩnh',
  'supabase': 'xu-pa-bây',
  'swagger': 'sờ-goác-gơ',
  'swot analysis': 'xoát a-na-ly-sít',
  'tailwind': 'teo-uin',
  'tailwind css': 'tên-uynh c-s-s',
  'task contract': 'tát-xơ con-trắc',
  'tech lead': 'tếch lít',
  'technical ba': 'tếch-ni-cồ bi-ây',
  'technical debt': 'tếch-ni-cồ đét',
  'tensorflow': 'ten-sờ-phlâu',
  'terminal': 'tơ-mi-nần',
  'tester': 'tét-tơ',
  'thinks': 'thinh',
  'timeline': 'tai-lai',
  'timezone': 'u-tê-xê',
  'to-be': 'tu-bi',
  'token': 'tô-cần',
  'traceability matrix': 'tờ-rây-xa-bi-li-ti mê-trích',
  'trade-off': 'tờ-rết-ọp',
  'transformer': 'trăn-pho-mơ',
  'trend': 'chen',
  'tts': 'ti-ti-ét',
  'typescript': 'tai-sờ-cơ-ríp',
  'uat': 'u-a-tê',
  'uber': 'u-bơ',
  'ui': 'u-ai',
  'ui/ux': 'u-ai yu-ec',
  'unit test': 'yu-nít tết',
  'url': 'u-ar-el',
  'usb': 'diu-ét-bi',
  'usb-c': 'ui-ét-bi-ci',
  'use case': 'yêu-kết',
  'use-case': 'yêu-kết',
  'user journey map': 'yiu-dơ gơ-ni mép',
  'user story': 'yiu-dơ sờ-to-ri',
  'user story mapping': 'yiu-dơ sờ-to-ri mép-ping',
  'utc': 'u-t-c',
  'ux': 'u-ích',
  'v8 engine': 'vi-tám en-jin',
  'velocity': 'vê-lo-xi-ti',
  'vercel': 'vơ-xen',
  'verceljs': 'vơ-xen-chây-ét',
  'vibe coding': 'vai-bơ cốt-đinh',
  'video': 'vi-đê-ô',
  'vietqr': 'viết-quy-rờ',
  'vite': 'vít',
  'vneid': 'v-n-e-i-d',
  'voucher': 'vao-chơ',
  'vr': 'vi-a',
  'webhook': 'oép-húc',
  'website': 'oét-sai',
  'whisper': 'uít-xpơ',
  'wi-fi': 'uai-fai',
  'wireframe': 'oai-phờ-rem',
  'word': 'uất',
  'xr': 'ích-a',
  'zoom': 'rum',
};

const TECH_TERMS_WHITELIST = new Set([
  'prompt', 'react', 'api', 'vite', 'nextjs', 'next.js', 'nodejs', 'node.js', 'javascript', 'typescript',
  'css', 'html', 'npm', 'json', 'sql', 'cli', 'git', 'github', 'docker', 'aws', 'vercel',
  'remotion', 'video', 'marketing', 'dashboard', 'animation', 'avatar', 'website', 'logo',
  'brand', 'component', 'framework', 'timeline', 'audio', 'mp4', 'mp3', 'client', 'server',
  'app', 'dev', 'build', 'deploy', 'code', 'database', 'ai', 'gpt', 'llm', 'agent', 'premiere',
  'capcut', 'photoshop', 'illustrator', 'canva', 'figma', 'ui', 'ux', 'front-end', 'back-end',
  'gpt-4', 'gpt-3', 'gpt4', 'gpt3',
  // Dynamic whitelist from new keys
  ...Object.keys(TECH_TERMS_TRANSLITERATION)
]);

module.exports = {
  TECH_TERMS_TRANSLITERATION,
  TECH_TERMS_WHITELIST
};
